---
title: 'Ransomware attack hits major US data center provider'
date: 2019-12-05T05:53:00+01:00
draft: false
---

![cloud server rack](https://zdnet1.cbsistatic.com/hub/i/2019/03/05/6f698477-11a6-48ae-bed5-ef5b5d85f52c/fcac0c976c02d1503230414a667d8f8a/cloud-server.jpg)

[CyrusOne](https://cyrusone.com/), one of the biggest data center providers in the US, has suffered a ransomware attack, ZDNet has learned.

CyrusOne is currently working with law enforcement and forensics firms to investigate the attack and is also helping customers restore lost data from backups.

The incident took place yesterday and was caused by a version of the REvil (Sodinokibi) ransomware.

This is the same ransomware family that hit [several managed service providers](https://www.zdnet.com/article/ransomware-gang-hacks-msps-to-deploy-ransomware-on-customer-systems/) in June, [over 20 Texas local governments](https://www.zdnet.com/article/at-least-20-texas-local-governments-hit-in-coordinated-ransomware-attack/) in early August, and [400+ US dentist offices](https://www.zdnet.com/article/ransomware-hits-hundreds-of-dentist-offices-in-the-us/) in late August.

According to a copy of the ransom note obtained by ZDNet, this was a targeted attack against the company's network. The point of entry is currently unknown.

![cyrusone-ransom-note.png](https://www.zdnet.com/article/ransomware-attack-hits-major-us-data-center-provider/#ftag=RSSbaffb68)

<span><img src="https://zdnet1.cbsistatic.com/hub/i/2019/12/05/c6fe343d-161a-4ec2-9b49-d3562b5e38ca/d73904332615745b0b8dfa3a0a0b8bde/cyrusone-ransom-note.png" alt="cyrusone-ransom-note.png" /></span>

CyrusOne has not yet publicly disclosed the incident. A CyrusOne spokesperson was not available for comment, either via phone call, email, or a live support chat via the company's website.

FIA Tech, a financial and brokerage firm, has informed customers today that an outage of their respective cloud services originated at their data center provider. FIA Tech did not name the data center provider, but a quick search identified it as CyrusOne.

[In a message to customers](https://support.fia-tech.com/hc/en-us/articles/360039830553-Dec-2nd-Notification-to-FIA-Tech-System-Users-Information-on-FIA-Tech-Outage), FIA Tech said "the attack was focused on disrupting operations in an attempt to obtain a ransom from our data center provider."

A source has told ZDNet today that the incident has not impacted all of CyrusOne's data centers, but that restoring servers and customer data will be a lengthy process. We've been told CyrusOne does not intend to pay the ransom demand, barring any future unforeseen developments.

The company owns 45 data centers in Europe, Asia, and the Americas, and has more than 1,000 customers. It is also considering a sale after receiving takeover interest over the summer, [according to Bloomberg](https://www.bloomberg.com/news/articles/2019-09-19/cyrusone-is-said-to-draw-interest-from-rival-digital-realty).

CyrusOne is a publicly-traded, NASDAQ-listed company ([NASDAQ:CONE](https://www.nasdaq.com/market-activity/stocks/cone)). In an SEC filing last year, the company explicitly listed "ransomware" as a risk factor for its business ([page 23](http://investor.cyrusone.com/node/11856/html)).

_A copy of the ransomware executable that is believed to have infected the company's network was [uploaded on VirusTotal](https://www.virustotal.com/gui/file/6ff970f1502347acd2d00e7746e40fba48995abbe26271d13102753c55694078/community) earlier today._

  
  
from Latest Topic for ZDNet in... https://ift.tt/2reN3tT